### ISSUE TITLE
Define themes

### ISSUE THREAD

**Issue by equinusocio** [wonderflow-bv/react-components#10]
## What

Define color schemes as `css` custom properties to be 

### Custom templates for themes

We need a way to customize the output templates, in order to use platform specific names decoupled from the token name:

```js
import tkns from '@wonderflow/tokens';

{
  '--my-custom-named-varì': `hsl(${tkns.primary[100]})`;
}
```

becomes

```css 
:root {
  --my-custom-named-var: hsl(0deg 0% 0%);
}
```
